#!/bin/sh
#

sed -i "s#helper/jsondata#helper/graphql#g" src/helper/config.ts

npm run build -- --base /nav/ --outDir dist/nav
rm -rf dist/nav/assets/logos

sed -i "s#helper/graphql#helper/jsondata#g" src/helper/config.ts
